//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSecretaria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AULA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AULA()
        {
            this.ALUNO = new HashSet<ALUNO>();
        }
    
        public int ID_AULA { get; set; }
        public Nullable<int> ID_PROFESSOR { get; set; }
        public System.DateTime DATA_AULA { get; set; }
        public Nullable<System.TimeSpan> HORA_INICIO { get; set; }
        public Nullable<System.TimeSpan> HORA_FIM { get; set; }
    
        public virtual PROFESSOR PROFESSOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ALUNO> ALUNO { get; set; }
    }
}
