//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSecretaria.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class eSecretariaEntities : DbContext
    {
        public eSecretariaEntities()
            : base("name=eSecretariaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ALUNO> ALUNO { get; set; }
        public virtual DbSet<AULA> AULA { get; set; }
        public virtual DbSet<DISCIPLINA> DISCIPLINA { get; set; }
        public virtual DbSet<PROFESSOR> PROFESSOR { get; set; }
    }
}
